import "dotenv/config";
import { db } from "./index";
import { agents, events, offers, contactRequests, reviews } from "./schema";
import { pexels } from "@/lib/format";

const daysFromNow = (n: number) => new Date(Date.now() + n * 86_400_000);
const daysFromNow2 = daysFromNow;
const hoursAgo = (n: number) => new Date(Date.now() - n * 3_600_000);

async function seed() {
  console.log("Clearing marketplace tables…");
  await db.delete(events);
  await db.delete(contactRequests);
  await db.delete(reviews);
  await db.delete(offers);
  await db.delete(agents);

  const [ufuq, harmain, diwan, ruh, caucasus, mediterranean, visa, saira, coast] =
    await db
      .insert(agents)
      .values([
        {
          displayName: "وكالة أفق السفر",
          latinName: "Ufuq Travel",
          bio: "وكالة سعودية تأسست عام ٢٠١٦، متخصصة في الباقات العائلية المدروسة وبرامج الخليج القصيرة. فريق صغير يراجع كل برنامج على الأرض قبل نشره، ولا نبيع وجهة لم نمشِ فيها بأنفسنا.",
          photoUrl: pexels(37409495, true),
          city: "الرياض",
          country: "السعودية",
          licenseType: "agency",
          licenseNumber: "73101244",
          verificationStatus: "verified",
          verifiedAt: hoursAgo(24 * 900),
          specialtyTags: ["باقات عائلية", "الخليج", "البحر الأحمر"],
          languages: ["العربية", "الإنجليزية"],
          responseRate: 96,
          avgResponseHours: 3.2,
          totalTrips: 1240,
          joinedAt: hoursAgo(24 * 1000),
        },
        {
          displayName: "بوابة الحرمين للعمرة",
          latinName: "Harmain Gate",
          bio: "متخصصون في برامج العمرة والزيارة منذ ٢٠١١. مقرّنا جدة، ومرشدونا يرافقون كل حملة من المطار إلى المطار. نشرنا برامج لأكثر من ٤٠ ألف معتمر بإشراف وزارة الحج والعمرة.",
          photoUrl: pexels(7984731, true),
          city: "جدة",
          country: "السعودية",
          licenseType: "agency",
          licenseNumber: "73100965",
          verificationStatus: "verified",
          verifiedAt: hoursAgo(24 * 1100),
          specialtyTags: ["عمرة", "زيارة", "حملات مرافقة"],
          languages: ["العربية", "الإنجليزية", "الأردية"],
          responseRate: 98,
          avgResponseHours: 1.8,
          totalTrips: 3210,
          joinedAt: hoursAgo(24 * 1200),
        },
        {
          displayName: "سفريات الديوان",
          latinName: "Diwan Travel",
          bio: "مستشار سفر مستقل يعمل من الدمام. أصمّم برامج البلقان وأوروبا الشرقية بعناية شخصية — أعرف سراييفو كما أعرف الخبر، وأسافر مع مجموعاتي بنفسي مرتين في السنة.",
          photoUrl: pexels(17086317, true),
          city: "الدمام",
          country: "السعودية",
          licenseType: "individual",
          licenseNumber: null,
          verificationStatus: "verified",
          verifiedAt: hoursAgo(24 * 700),
          specialtyTags: ["البلقان", "أوروبا الشرقية", "طيران"],
          languages: ["العربية", "الإنجليزية"],
          responseRate: 92,
          avgResponseHours: 5,
          totalTrips: 486,
          joinedAt: hoursAgo(24 * 800),
        },
        {
          displayName: "روح الشرق للسياحة",
          latinName: "Ruh Al Sharq",
          bio: "بوتيك سياحي في دبي لشهر العسل والوجهات الاستوائية. نتفاوض مباشرة مع المنتجعات في المالديف وجنوب شرق آسيا، ونضمن مطابقة الفيلا للصور قبل تأكيد أي حجز.",
          photoUrl: pexels(16900960, true),
          city: "دبي",
          country: "الإمارات",
          licenseType: "agency",
          licenseNumber: "DTCM-88214",
          verificationStatus: "verified",
          verifiedAt: hoursAgo(24 * 500),
          specialtyTags: ["شهر العسل", "المالديف", "جنوب شرق آسيا"],
          languages: ["العربية", "الإنجليزية", "الفرنسية"],
          responseRate: 94,
          avgResponseHours: 2.5,
          totalTrips: 860,
          joinedAt: hoursAgo(24 * 600),
        },
        {
          displayName: "أجنحة القوقاز",
          latinName: "Caucasus Wings",
          bio: "أول وكالة سعودية متخصصة حصرياً في القوقاز. جورجيا وأذربيجان وأرمينيا ببرامج أسبوعية مضمونة الانطلاق، ومرشدون يتكلمون العربية في كل رحلة.",
          photoUrl: pexels(16759943, true),
          city: "الرياض",
          country: "السعودية",
          licenseType: "agency",
          licenseNumber: "73101501",
          verificationStatus: "verified",
          verifiedAt: hoursAgo(24 * 800),
          specialtyTags: ["جورجيا", "أذربيجان", "أرمينيا"],
          languages: ["العربية", "الإنجليزية", "الروسية"],
          responseRate: 97,
          avgResponseHours: 1.2,
          totalTrips: 1540,
          joinedAt: hoursAgo(24 * 950),
        },
        {
          displayName: "مسارات المتوسط",
          latinName: "Mediterranean Routes",
          bio: "وكيل مستقل من جدة يعشق المتوسط. تركيا بكل مواسمها والمغرب الأصيل بمساراته القديمة — برامج صغيرة العدد، وفنادق بوتيك مختارة بيدي لا بالكتالوج.",
          photoUrl: pexels(17086320, true),
          city: "جدة",
          country: "السعودية",
          licenseType: "individual",
          licenseNumber: null,
          verificationStatus: "verified",
          verifiedAt: hoursAgo(24 * 400),
          specialtyTags: ["تركيا", "المغرب", "فنادق بوتيك"],
          languages: ["العربية", "الإنجليزية", "التركية"],
          responseRate: 89,
          avgResponseHours: 6,
          totalTrips: 372,
          joinedAt: hoursAgo(24 * 550),
        },
        {
          displayName: "نخبة التأشيرات",
          latinName: "Visa Elite",
          bio: "مكتب متخصص في ملفات التأشيرات فقط — شنغن، بريطانيا، أمريكا. نراجع الملف سطراً سطراً قبل التقديم، ونخبرك بصراحة إن كانت فرصك ضعيفة قبل أن تدفع ريالاً واحداً.",
          photoUrl: pexels(9623647, true),
          city: "الرياض",
          country: "السعودية",
          licenseType: "individual",
          licenseNumber: null,
          verificationStatus: "verified",
          verifiedAt: hoursAgo(24 * 1050),
          specialtyTags: ["تأشيرات", "شنغن", "بريطانيا"],
          languages: ["العربية", "الإنجليزية"],
          responseRate: 99,
          avgResponseHours: 0.9,
          totalTrips: 2210,
          joinedAt: hoursAgo(24 * 1150),
        },
        {
          displayName: "سيرا ترافل",
          latinName: "Saira Travel",
          bio: "وكالة مصرية عريقة من قلب القاهرة. كروز النيل بضيافتنا منذ ٢٠٠٩، وبرامج البحر الأحمر بعقود مباشرة مع المراكب والمنتجعات — السعر الذي تراه هو السعر النهائي.",
          photoUrl: pexels(20727581, true),
          city: "القاهرة",
          country: "مصر",
          licenseType: "agency",
          licenseNumber: "EG-44190",
          verificationStatus: "verified",
          verifiedAt: hoursAgo(24 * 600),
          specialtyTags: ["كروز النيل", "مصر", "البحر الأحمر"],
          languages: ["العربية", "الإنجليزية"],
          responseRate: 93,
          avgResponseHours: 4,
          totalTrips: 980,
          joinedAt: hoursAgo(24 * 700),
        },
        {
          displayName: "ساحل ومدار",
          latinName: "Coast & Meridian",
          bio: "وكالة قطرية للإقامات الفاخرة القصيرة. عطلات نهاية أسبوع مدروسة في دبي والدوحة والبحرين بفنادق خمس نجوم حقيقية، مع تأكيد فوري وإلغاء مرن حتى ٧٢ ساعة.",
          photoUrl: pexels(16900961, true),
          city: "الدوحة",
          country: "قطر",
          licenseType: "agency",
          licenseNumber: "QTA-7712",
          verificationStatus: "verified",
          verifiedAt: hoursAgo(24 * 300),
          specialtyTags: ["إقامات فاخرة", "دبي", "عطلات قصيرة"],
          languages: ["العربية", "الإنجليزية"],
          responseRate: 95,
          avgResponseHours: 2.1,
          totalTrips: 715,
          joinedAt: hoursAgo(24 * 420),
        },
      ])
      .returning();

  console.log("Inserting offers…");
  const [, harmainUmrah] = [ufuq, harmain];
  await db.insert(offers).values([
    {
      agentId: harmainUmrah.id,
      title: "عمرة رمضان — عشرة أيام بجوار الحرم",
      titleEn: "Ramadan Umrah — 10 nights by the Haram",
      description:
        "برنامج العشر الأوسط من رمضان: إقامة في فندق خمس نجوم على بعد ١٥٠ متراً من ساحات الحرم، مع مصلى مخصص للحملة وقت الازدحام.\n\nالمرشد يرافق المجموعة من مطار الملك عبدالعزيز حتى العودة، ويشمل البرنامج زيارة للمعالم: غار حراء وجبل ثور ومزدلفة. المقاعد محدودة بـ ٤٥ معتمراً لكل حملة.",
      tripType: "umrah",
      originCity: "جدة",
      destinationCity: "مكة المكرمة",
      destinationCountry: "السعودية",
      destinationCountryEn: "Saudi Arabia",
      departureDate: daysFromNow(160),
      durationDays: 10,
      priceAmount: 9800,
      currency: "SAR",
      priceType: "per_person",
      includes: ["تأشيرة العمرة", "طيران مباشر ذهاب وعودة", "إقامة ٥ نجوم قرب الحرم", "مواصلات داخلية حديثة", "إفطار وسحور يومياً", "مرشد مرافق طيلة البرنامج"],
      excludes: ["الوجبات الإضافية", "المصاريف الشخصية", "التأمين الطبي الاختياري"],
      minTravelers: 1,
      maxTravelers: 4,
      status: "published",
      heroImage: pexels(38546883),
      isFeatured: true,
      viewCount: 3120,
      contactCount: 61,
      publishedAt: daysFromNow(-21),
      expiresAt: daysFromNow(6),
      createdAt: daysFromNow(-21),
    },
    {
      agentId: caucasus.id,
      title: "جورجيا الخضراء — تبليسي وكازبيجي سبعة أيام",
      titleEn: "Green Georgia — Tbilisi & Kazbegi, 7 days",
      description:
        "برنامجنا الأشهر منذ خمس سنوات: ثلاث ليالٍ في تبليسي القديمة، وثلاث في جبال كازبيجي بإطلالة على كنيسة جيرجيتي، مع يوم كامل في وادي الحمامات الكبريتية.\n\nالسعر «يبدأ من» يعتمد على فئة الفندق؛ الفرق بين الاقتصادي والفاخر موضح بسطر واحد في عرض السعر، بلا مفاجآت عند الدفع.",
      tripType: "package",
      originCity: "الرياض",
      destinationCity: "تبليسي",
      destinationCountry: "جورجيا",
      destinationCountryEn: "Georgia",
      departureDate: daysFromNow(34),
      durationDays: 7,
      priceAmount: 4200,
      currency: "SAR",
      priceType: "starting_from",
      includes: ["طيران مباشر ذهاب وعودة", "فنادق ٤ نجوم مع إفطار", "مرشد يتكلم العربية", "جولة كازبيجي بسيارات دفع رباعي", "شرائح إنترنت محلية"],
      excludes: ["تذاكر التلفريك", "الغداء والعشاء", "المصاريف الشخصية"],
      minTravelers: 2,
      maxTravelers: 12,
      status: "published",
      heroImage: pexels(38723717),
      isFeatured: true,
      viewCount: 2240,
      contactCount: 44,
      publishedAt: daysFromNow(-12),
      expiresAt: daysFromNow(45),
      createdAt: daysFromNow(-12),
    },
    {
      agentId: caucasus.id,
      title: "أذربيجان — باكو وجبال القوقاز ستة أيام",
      titleEn: "Azerbaijan — Baku & the Caucasus, 6 days",
      description:
        "باكو الحديثة وشوارعها الحجرية، ثم يومان في قوبا وشاكي بين الغابات والخانات القديمة. البرنامج مصمم لمن زار جورجيا ويريد العمق نفسه بوجهة جديدة.\n\nيشمل العرض المتحف الوطني للسجاد وليلة في خان شاكي التاريخي — تجربة لا تُباع في الكتالوجات العامة.",
      tripType: "package",
      originCity: "الرياض",
      destinationCity: "باكو",
      destinationCountry: "أذربيجان",
      destinationCountryEn: "Azerbaijan",
      departureDate: daysFromNow(76),
      durationDays: 6,
      priceAmount: 3900,
      currency: "SAR",
      priceType: "starting_from",
      includes: ["طيران ذهاب وعودة", "فنادق ٤ نجوم", "مرشد عربي", "ليلة خان شاكي التاريخي", "دخول المتاحف المذكورة"],
      excludes: ["الوجبات غير المذكورة", "التأمين"],
      minTravelers: 2,
      maxTravelers: 14,
      status: "published",
      heroImage: pexels(37612863),
      isFeatured: false,
      viewCount: 1130,
      contactCount: 19,
      publishedAt: daysFromNow(-8),
      expiresAt: daysFromNow(60),
      createdAt: daysFromNow(-8),
    },
    {
      agentId: visa.id,
      title: "تأشيرة شنغن — ملف كامل مع موعد مضمون",
      titleEn: "Schengen visa — full file preparation",
      description:
        "إعداد ملف التأشيرة من الألف إلى الياء: استشارة أولى مجانية لتقييم الملف، ثم تجهيز النماذج والحجوزات المؤقتة والتأمين وخطاب التغطية، وحجز موعد التقديم.\n\nلا نَعِد بالقبول — لا أحد يستطيع ذلك بأمانة — لكننا نعدك بملف لا يُرفض لسبب إجرائي. نسبة قبول ملفاتنا المكتملة ٩٤٪ خلال الـ ١٢ شهراً الماضية.",
      tripType: "visa",
      originCity: "الرياض",
      destinationCity: "أوروبا",
      destinationCountry: "منطقة شنغن",
      destinationCountryEn: "Schengen",
      departureDate: null,
      durationDays: null,
      priceAmount: 950,
      currency: "SAR",
      priceType: "per_person",
      includes: ["استشارة تقييم مجانية", "إعداد النماذج والحجوزات المؤقتة", "تأمين سفر معتمد", "حجز موعد التقديم", "متابعة حتى صدور النتيجة"],
      excludes: ["رسوم السفارة", "رسوم مركز التقديم VFS/TLS"],
      minTravelers: 1,
      maxTravelers: 6,
      status: "published",
      heroImage: pexels(32447869),
      isFeatured: false,
      viewCount: 2890,
      contactCount: 53,
      publishedAt: daysFromNow(-30),
      expiresAt: daysFromNow(40),
      createdAt: daysFromNow(-30),
    },
    {
      agentId: visa.id,
      title: "تأشيرة بريطانيا — ملف وموعد بيومتري",
      titleEn: "UK visa — file & biometrics appointment",
      description:
        "نفس منهج الشنغن لتأشيرة الزيارة البريطانية: تقييم صريح للملف، إعداد كامل، وحجز الموعد البيومتري في الرياض أو جدة.",
      tripType: "visa",
      originCity: "جدة",
      destinationCity: "لندن",
      destinationCountry: "بريطانيا",
      destinationCountryEn: "United Kingdom",
      departureDate: null,
      durationDays: null,
      priceAmount: 1150,
      currency: "SAR",
      priceType: "per_person",
      includes: ["تقييم الملف", "إعداد الطلب كاملاً", "حجز الموعد البيومتري", "متابعة القرار"],
      excludes: ["رسوم التأشيرة الحكومية", "خدمة الأولوية الاختيارية"],
      minTravelers: 1,
      maxTravelers: 4,
      status: "published",
      heroImage: pexels(16900964),
      isFeatured: false,
      viewCount: 980,
      contactCount: 17,
      publishedAt: daysFromNow(-18),
      expiresAt: daysFromNow(38),
      createdAt: daysFromNow(-18),
    },
    {
      agentId: ruh.id,
      title: "المالديف — شهر عسل في فيلا مائية خمس ليالٍ",
      titleEn: "Maldives honeymoon — 5 nights overwater",
      description:
        "خمس ليالٍ في فيلا مائية بمسبح خاص في شمال ماليه أتول — السعر للثنائي ويشمل الطيران الداخلي بالطائرة المائية، ونصف إقامة، وجلسة تصوير غروب مجانية من المنتجع.\n\nقبل التأكيد نرسل لك فيديو حي للفيلا نفسها المتاحة لتواريخك — لا صور أرشيف ولا وعود عامة.",
      tripType: "hotel",
      originCity: "الرياض",
      destinationCity: "ماليه",
      destinationCountry: "المالديف",
      destinationCountryEn: "Maldives",
      departureDate: null,
      durationDays: 5,
      priceAmount: 14500,
      currency: "SAR",
      priceType: "per_group",
      includes: ["فيلا مائية بمسبح خاص (للثنائي)", "طائرة مائية ذهاب وعودة", "إفطار وعشاء يومياً", "جلسة تصوير غروب", "تأكيد فوري خلال ٦ ساعات"],
      excludes: ["الطيران الدولي", "الرياضات المائية الميكانيكية", "الضرائب البيئية للجزيرة"],
      minTravelers: 2,
      maxTravelers: 3,
      status: "published",
      heroImage: pexels(27099922),
      isFeatured: true,
      viewCount: 1980,
      contactCount: 38,
      publishedAt: daysFromNow(-15),
      expiresAt: daysFromNow(9),
      createdAt: daysFromNow(-15),
    },
    {
      agentId: mediterranean.id,
      title: "إسطنبول وطرابزون — ثمانية أيام على ساحلين",
      titleEn: "Istanbul & Trabzon — 8 days, two coasts",
      description:
        "أربع ليالٍ في إسطنبول بفندق بوتيك في سلطان أحمد، وأربع في طرابزون بكوخ مطل على مرتفعات أوزنجول. مزيج يوازن المدينة والضباب.\n\nالمجموعات حتى ١٠ أشخاص فقط، وسائق خاص طيلة البرنامج، ويوم حر كامل في إسطنبول لمن يعرف قلبه.",
      tripType: "package",
      originCity: "جدة",
      destinationCity: "إسطنبول",
      destinationCountry: "تركيا",
      destinationCountryEn: "Türkiye",
      departureDate: daysFromNow(27),
      durationDays: 8,
      priceAmount: 5400,
      currency: "SAR",
      priceType: "starting_from",
      includes: ["طيران ذهاب وعودة", "فنادق بوتيك مع إفطار", "سائق خاص", "جولة البوسفور بقارب خاص", "مرشد مرافق"],
      excludes: ["الغداء والعشاء", "تذاكر الداخل المدفوعة", "التأمين"],
      minTravelers: 2,
      maxTravelers: 10,
      status: "published",
      heroImage: pexels(31256089),
      isFeatured: false,
      viewCount: 1420,
      contactCount: 22,
      publishedAt: daysFromNow(-10),
      expiresAt: daysFromNow(50),
      createdAt: daysFromNow(-10),
    },
    {
      agentId: mediterranean.id,
      title: "كابادوكيا — فجر البالونات خمسة أيام",
      titleEn: "Cappadocia — balloon dawn, 5 days",
      description:
        "ثلاث ليالٍ في فندق كهفي في جوريمة، وإقلاع فجر الجمعة بالبالون (مؤكد مسبقاً ومرتبط بالطقس لا بالحظ)، وجولة الوديان الحمراء والمدينة تحت الأرض.\n\nنحجز رحلة البالون من المصدر الرسمي ونسترجع قيمتها كاملة إن أُلغيت لسوء الطقس — بند مكتوب لا عبارة تسويقية.",
      tripType: "package",
      originCity: "الرياض",
      destinationCity: "كابادوكيا",
      destinationCountry: "تركيا",
      destinationCountryEn: "Türkiye",
      departureDate: daysFromNow(97),
      durationDays: 5,
      priceAmount: 4800,
      currency: "SAR",
      priceType: "per_person",
      includes: ["طيران داخلي وخارجي", "فندق كهفي مع إفطار", "رحلة بالون مؤكدة", "جولة الوديان والمدينة تحت الأرض"],
      excludes: ["الوجبات المسائية", "التأمين"],
      minTravelers: 2,
      maxTravelers: 12,
      status: "published",
      heroImage: pexels(30370450),
      isFeatured: false,
      viewCount: 860,
      contactCount: 11,
      publishedAt: daysFromNow(-6),
      expiresAt: daysFromNow(55),
      createdAt: daysFromNow(-6),
    },
    {
      agentId: saira.id,
      title: "كروز النيل — أسوان إلى الأقصر أربع ليالٍ",
      titleEn: "Nile cruise — Aswan to Luxor, 4 nights",
      description:
        "أربع ليالٍ على متن مركب خمس نجوم من أسوان إلى الأقصر: الكرنك، الأقصر، إدفو، كوم أمبو، وفيلة — مع عالم مصريات يرافق المجموعة في كل معلم.\n\nالسعر النهائي يشمل كل الرسوم والإكراميات الإلزامية — بندًا بندًا في عرض السعر قبل الدفع.",
      tripType: "cruise",
      originCity: "القاهرة",
      destinationCity: "أسوان",
      destinationCountry: "مصر",
      destinationCountryEn: "Egypt",
      departureDate: daysFromNow(52),
      durationDays: 4,
      priceAmount: 6700,
      currency: "SAR",
      priceType: "per_person",
      includes: ["مقصورة خارجية بإطلالة نيلية", "إقامة كاملة الوجبات", "جميع الجولات مع عالم مصريات", "رسوم المعالم والإكراميات"],
      excludes: ["الطيران الدولي إلى القاهرة", "المشروبات"],
      minTravelers: 1,
      maxTravelers: 8,
      status: "published",
      heroImage: pexels(37559111),
      isFeatured: false,
      viewCount: 1210,
      contactCount: 16,
      publishedAt: daysFromNow(-14),
      expiresAt: daysFromNow(44),
      createdAt: daysFromNow(-14),
    },
    {
      agentId: mediterranean.id,
      title: "المغرب الأصيل — مراكش وفاس والصحراء ثمانية أيام",
      titleEn: "Authentic Morocco — Marrakech, Fes & the Sahara",
      description:
        "من أزقة فاس العتيقة إلى ليلة في مخيم صحراوي عند كثبان مرزوكة: رياضات تاريخية، طريق القصبات، وجلسة شاي نعناع لا تنتهي.\n\nنمشي المدن القديمة مع مرشدين محليين مرخصين، وننام في رياضات لا يتجاوز عدد غرفها عشراً.",
      tripType: "package",
      originCity: "جدة",
      destinationCity: "مراكش",
      destinationCountry: "المغرب",
      destinationCountryEn: "Morocco",
      departureDate: daysFromNow(90),
      durationDays: 8,
      priceAmount: 7200,
      currency: "SAR",
      priceType: "starting_from",
      includes: ["طيران ذهاب وعودة", "رياضات تاريخية مع إفطار", "ليلة مخيم صحراوي فاخر", "قافلة جمال عند الغروب", "مرشدون محليون مرخصون"],
      excludes: ["الغداء والعشاء خارج المخيم", "التأمين"],
      minTravelers: 2,
      maxTravelers: 12,
      status: "published",
      heroImage: pexels(15260622),
      isFeatured: true,
      viewCount: 1560,
      contactCount: 27,
      publishedAt: daysFromNow(-9),
      expiresAt: daysFromNow(58),
      createdAt: daysFromNow(-9),
    },
    {
      agentId: diwan.id,
      title: "البوسنة والهرسك — سراييفو وموستار سبعة أيام",
      titleEn: "Bosnia — Sarajevo & Mostar, 7 days",
      description:
        "سراييفو التي يعرفها قلبي قبل خرائطي: أربع ليالٍ في العاصمة وثلاث موزعة بين موستار وبلاغاي وشلالات كرافيتسا، بمجموعة لا تتجاوز عشرة.\n\nأرافق هذه المجموعة بنفسي — هذه رحلتي التي أقودها مرتين في السنة، وليست مسحوبة من مورّد.",
      tripType: "package",
      originCity: "الدمام",
      destinationCity: "سراييفو",
      destinationCountry: "البوسنة والهرسك",
      destinationCountryEn: "Bosnia & Herzegovina",
      departureDate: daysFromNow(43),
      durationDays: 7,
      priceAmount: 5900,
      currency: "SAR",
      priceType: "starting_from",
      includes: ["طيران ذهاب وعودة", "فنادق ٤ نجوم وسط المدينة", "مرشد يتكلم العربية", "جولة شلالات كرافيتسا", "مصلى مخصص وقت الجمعة"],
      excludes: ["الوجبات غير المذكورة", "التأمين"],
      minTravelers: 2,
      maxTravelers: 10,
      status: "published",
      heroImage: pexels(32447869),
      isFeatured: false,
      viewCount: 1740,
      contactCount: 25,
      publishedAt: daysFromNow(-16),
      expiresAt: daysFromNow(47),
      createdAt: daysFromNow(-16),
    },
    {
      agentId: diwan.id,
      title: "طيران مباشر — الرياض إلى سراييفو ذهاب وعودة",
      titleEn: "Direct flight — Riyadh to Sarajevo return",
      description:
        "مقاعد مؤكدة على الرحلة المباشرة الموسمية: أمتعة ٣٠ كجم واختيار مقعد مسبق مشمولان. مناسب لمن رتّب فندقه بنفسه ويريد سعر طيران نظيفاً بلا تحويلات خفية.",
      tripType: "flight",
      originCity: "الرياض",
      destinationCity: "سراييفو",
      destinationCountry: "البوسنة والهرسك",
      destinationCountryEn: "Bosnia & Herzegovina",
      departureDate: daysFromNow(43),
      durationDays: null,
      priceAmount: 1650,
      currency: "SAR",
      priceType: "per_person",
      includes: ["أمتعة ٣٠ كجم", "اختيار مقعد مسبق", "تعديل التاريخ مقابل فرق السعر فقط"],
      excludes: ["الفندق", "المواصلات"],
      minTravelers: 1,
      maxTravelers: 9,
      status: "published",
      heroImage: pexels(18037875),
      isFeatured: false,
      viewCount: 2310,
      contactCount: 31,
      publishedAt: daysFromNow(-20),
      expiresAt: daysFromNow(12),
      createdAt: daysFromNow(-20),
    },
    {
      agentId: coast.id,
      title: "دبي للعائلات — أربع ليالٍ خمس نجوم على المارينا",
      titleEn: "Dubai for families — 4 nights, five stars",
      description:
        "أربع ليالٍ بغرفة مزدوجة في فندق خمس نجوم فعلي على المارينا — تأكيد فوري، إلغاء مجاني حتى ٧٢ ساعة، وسرير أطفال وإفطار مشمولان بلا رسوم إضافية.\n\nالسعر للغرفة وليس للفرد، ونرسل اسم الفندق والغرفة قبل الدفع — لا «أو ما يعادلها».",
      tripType: "hotel",
      originCity: "الرياض",
      destinationCity: "دبي",
      destinationCountry: "الإمارات",
      destinationCountryEn: "UAE",
      departureDate: null,
      durationDays: 4,
      priceAmount: 8400,
      currency: "AED",
      priceType: "per_group",
      includes: ["٤ ليالٍ غرفة مزدوجة مطلة", "إفطار يومي", "سرير أطفال مجاني", "إلغاء مجاني حتى ٧٢ ساعة", "تأكيد فوري"],
      excludes: ["الطيران", "رسوم السياحة الليلية للفندق"],
      minTravelers: 2,
      maxTravelers: 4,
      status: "published",
      heroImage: pexels(30554306),
      isFeatured: true,
      viewCount: 2680,
      contactCount: 42,
      publishedAt: daysFromNow(-11),
      expiresAt: daysFromNow(30),
      createdAt: daysFromNow(-11),
    },
    {
      agentId: ufuq.id,
      title: "أملج — مالديف السعودية ثلاثة أيام",
      titleEn: "Umluj — the Saudi Maldives, 3 days",
      description:
        "شاليه مطل على البحر الأحمر في أملج، رحلة قارب للدلافين والشعاب، وشواء غروب على الرمال. برنامج قصير مصمم لعطلة نهاية أسبوع كاملة الدهشة.\n\nمغادرة الخميس فجراً وعودة السبت ليلاً — مناسب حتى لمن لا يملك إجازة.",
      tripType: "package",
      originCity: "الرياض",
      destinationCity: "أملج",
      destinationCountry: "السعودية",
      destinationCountryEn: "Saudi Arabia",
      departureDate: daysFromNow(11),
      durationDays: 3,
      priceAmount: 2900,
      currency: "SAR",
      priceType: "starting_from",
      includes: ["شاليه مطل على البحر", "رحلة قارب للدلافين", "معدات غطس", "شواء غروب", "مواصلات من المطار"],
      excludes: ["الطيران الداخلي", "المشروبات"],
      minTravelers: 2,
      maxTravelers: 8,
      status: "published",
      heroImage: pexels(28969401),
      isFeatured: false,
      viewCount: 940,
      contactCount: 14,
      publishedAt: daysFromNow(-7),
      expiresAt: daysFromNow(21),
      createdAt: daysFromNow(-7),
    },
    {
      agentId: ruh.id,
      title: "بوكيت وكوه بي بي — ستة أيام عائلية",
      titleEn: "Phuket & Phi Phi — 6 family days",
      description:
        "فيلا عائلية بمسبح خاص في كامالا، يوم كامل في خليج بي بي بقارب طويل الذيل، وبرنامج أطفال صباحي حتى يتسنى للوالدين غداء هادئ لمرة واحدة في السنة.",
      tripType: "package",
      originCity: "الرياض",
      destinationCity: "بوكيت",
      destinationCountry: "تايلاند",
      destinationCountryEn: "Thailand",
      departureDate: daysFromNow(120),
      durationDays: 6,
      priceAmount: 6900,
      currency: "SAR",
      priceType: "per_person",
      includes: ["فيلا عائلية بمسبح خاص", "جولة خليج بي بي", "برنامج أطفال صباحي", "مواصلات خاصة"],
      excludes: ["الطيران الدولي", "الوجبات المسائية"],
      minTravelers: 2,
      maxTravelers: 6,
      status: "pending_review",
      heroImage: pexels(9080918),
      isFeatured: false,
      viewCount: 0,
      contactCount: 0,
      publishedAt: null,
      expiresAt: null,
      createdAt: hoursAgo(9),
    },
    {
      agentId: harmainUmrah.id,
      title: "عمرة شعبان — برنامج اقتصادي سبعة أيام",
      titleEn: "Shaban Umrah — economical 7-day program",
      description:
        "حملة شعبان الاقتصادية: فندق أربع نجوم على بعد ٦٠٠ متر مع مواصلات مكوكية كل نصف ساعة، ونفس المرافقة والتنظيم — بفئة سعرية أخف.",
      tripType: "umrah",
      originCity: "جدة",
      destinationCity: "مكة المكرمة",
      destinationCountry: "السعودية",
      destinationCountryEn: "Saudi Arabia",
      departureDate: daysFromNow(140),
      durationDays: 7,
      priceAmount: 5900,
      currency: "SAR",
      priceType: "per_person",
      includes: ["تأشيرة العمرة", "طيران اقتصادي", "فندق ٤ نجوم مع مواصلات مكوكية", "مرشد مرافق"],
      excludes: ["الوجبات", "المصاريف الشخصية"],
      minTravelers: 1,
      maxTravelers: 4,
      status: "pending_review",
      heroImage: pexels(35332385),
      isFeatured: false,
      viewCount: 0,
      contactCount: 0,
      publishedAt: null,
      expiresAt: null,
      createdAt: hoursAgo(26),
    },
    {
      agentId: mediterranean.id,
      title: "عرض الجمعة البيضاء — إسطنبول أربعة أيام",
      titleEn: "White Friday — Istanbul 4 days (delisted)",
      description:
        "عرض موسمي بسعر مخفض لفترة محدودة.\n\n(أُوقف العرض أثناء المراجعة — انظر سبب الرفض في لوحة المراجعة.)",
      tripType: "package",
      originCity: "جدة",
      destinationCity: "إسطنبول",
      destinationCountry: "تركيا",
      destinationCountryEn: "Türkiye",
      departureDate: daysFromNow(60),
      durationDays: 4,
      priceAmount: 999,
      currency: "SAR",
      priceType: "per_person",
      includes: ["طيران", "فندق مع إفطار"],
      excludes: [],
      minTravelers: 2,
      maxTravelers: 6,
      status: "rejected",
      rejectionReason:
        "السعر المعلن (٩٩٩ ريال) لا يشمل الضرائب والرسوم البالغة ~٧٤٠ ريالاً. يُحظر وفق سياسة المنصة تسعير لا يوضح التكلفة النهائية، وسياسة «يبدأ من» تتطلب جدول فروقات واضحاً. يمكنك إعادة التقديم بسعر شامل.",
      heroImage: pexels(35333141),
      isFeatured: false,
      viewCount: 0,
      contactCount: 0,
      publishedAt: null,
      expiresAt: null,
      createdAt: daysFromNow(-4),
    },
  ]).returning();

  console.log("Inserting reviews…");
  await db.insert(reviews).values([
    { agentId: caucasus.id, reviewerName: "أبو فهد", rating: 5, content: "رحلة جورجيا كانت منظمة لدرجة غير معهودة. المرشد عرف كل زاوية، والفروقات السعرية وُضحت من أول رسالة. جربت ثلاث وكالات قبلهم، لن أرجع.", isVerifiedTransaction: true, createdAt: hoursAgo(140) },
    { agentId: harmainUmrah.id, reviewerName: "أم سارة", rating: 5, content: "حملة رمضان الماضي كانت فوق الوصف. الفندق فعلاً قريب من الحرم كما في الإعلان، والمرشد وقف مع والدتي في كل التفاصيل. جزاهم الله خيراً.", isVerifiedTransaction: true, createdAt: hoursAgo(300) },
    { agentId: visa.id, reviewerName: "م. العتيبي", rating: 5, content: "قالوا لي بصراحة إن ملفي يحتاج تدعيماً قبل التقديم ووفروا عليّ رفضاً محققاً. قدّمت بعد شهرين وحصلت على شنغن متعددة. الصراحة تستحق الخمس نجوم.", isVerifiedTransaction: true, createdAt: hoursAgo(90) },
    { agentId: ruh.id, reviewerName: "نورة الشمري", rating: 5, content: "الفيلا كانت مطابقة للفيديو الذي أرسلوه بالمليمتر. شهر العسل مر بلا مفاجأة واحدة سيئة — وهذا أغلى ما تبيعه وكالة سفر.", isVerifiedTransaction: false, createdAt: hoursAgo(200) },
    { agentId: diwan.id, reviewerName: "خالد المطيري", rating: 4, content: "المحتوى والتنظيم ممتاز والمعرفة بالبوسنة شخصية فعلاً. تأخرت الردود مرة واحدة فقط في عطلة الأسبوع، ولهذا أربع نجوم لا خمس.", isVerifiedTransaction: true, createdAt: hoursAgo(250) },
    { agentId: coast.id, reviewerName: "أبو راشد", rating: 4, content: "الحجز سريع والفندق نفس ما وُعدنا به حرفياً. السعر النهائي مطابق للمعروض. تمنيت لو توفرت غرف متصلة للعائلات الكبيرة.", isVerifiedTransaction: false, createdAt: hoursAgo(120) },
    { agentId: ufuq.id, reviewerName: "ريما القحطاني", rating: 5, content: "برنامج أملج كان أجمل عطلة قصيرة مررنا بها. كل التفاصيل دقيقة، حتى موعد رحلة الدلافين. السعر النهائي هو نفسه المعروض.", isVerifiedTransaction: true, createdAt: hoursAgo(80) },
    { agentId: saira.id, reviewerName: "د. هشام", rating: 5, content: "عالم المصريات المرافق وحده يساوي نصف قيمة الرحلة. المركب نظيف والإكراميات محسوبة مسبقاً فمضت الرحلة بلا مواقف محرجة.", isVerifiedTransaction: true, createdAt: hoursAgo(400) },
    { agentId: mediterranean.id, reviewerName: "سلطان الحربي", rating: 4, content: "فنادق البوتيك المختارة موفقة جداً وخارج السائد. برنامج تركيا مريح الإيقاع رغم امتلائه. ينقصهم فقط تطبيق متابعة أفضل.", isVerifiedTransaction: false, createdAt: hoursAgo(160) },
    { agentId: caucasus.id, reviewerName: "هند العنزي", rating: 5, content: "سافرت معهم لجورجيا ثم أذربيجان في السنة نفسها. ثقة رابحتها الصراحة: قالوا لي لا تأخذي الباقة الفاخرة، الفرق لا يستحق. من قال هذا في سوقنا؟", isVerifiedTransaction: true, createdAt: hoursAgo(50) },
  ]);

  console.log("Seeding demo telemetry…");
  const offerRows = await db.select().from(offers);
  const telemetry: { name: string; offerId?: number; agentId?: number; meta?: string; createdAt: Date }[] = [];
  const demoCounts: [string, number][] = [
    ["landing_view", 96],
    ["search_submitted", 61],
    ["offer_viewed", 74],
    ["agent_viewed", 38],
    ["contact_started", 11],
    ["contact_submitted", 3],
  ];
  for (const [name, n] of demoCounts) {
    for (let i = 0; i < n; i++) {
      const sample = offerRows[i % offerRows.length];
      telemetry.push({
        name,
        offerId: name.includes("offer") || name.includes("contact") ? sample.id : undefined,
        agentId: name.includes("agent") || name.includes("contact") ? sample.agentId : undefined,
        createdAt: hoursAgo(Math.floor(Math.random() * 24 * 21) + 1),
      });
    }
  }
  await db.insert(events).values(telemetry);

  console.log("Inserting sample contact requests…");
  const geo = offerRows.find((o) => o.titleEn?.includes("Green Georgia"))!;
  const umrah = offerRows.find((o) => o.titleEn?.includes("Ramadan Umrah"))!;
  const maldives = offerRows.find((o) => o.titleEn?.includes("Maldives honeymoon"))!;

  await db.insert(contactRequests).values([
    {
      offerId: geo.id,
      agentId: geo.agentId,
      travelerName: "عبدالله السبيعي",
      travelerEmail: "a.alsubaie@example.com",
      message: "السلام عليكم — نحن أربعة أشخاص ونفضل تاريخ أكتوبر. هل الفرق بين الفئة الاقتصادية والفاخرة يستحق مع أطفال؟ وشكراً.",
      travelerCount: 4,
      travelDates: "أوائل أكتوبر ٢٠٢٦",
      status: "responded",
      createdAt: hoursAgo(30),
      respondedAt: hoursAgo(28),
    },
    {
      offerId: umrah.id,
      agentId: umrah.agentId,
      travelerName: "أم عبدالرحمن",
      travelerEmail: "umabd@example.com",
      message: "والدي كبير في السن ويحتاج كرسياً متحركاً في الطواف. هل يتوفر ضمن البرنامج؟ وهل الفندق مزود بمصاعد كافية؟",
      travelerCount: 3,
      travelDates: "رمضان ١٤٤٨",
      status: "viewed",
      createdAt: hoursAgo(7),
    },
    {
      offerId: maldives.id,
      agentId: maldives.agentId,
      travelerName: "فيصل الدوسري",
      travelerEmail: "f.aldossari@example.com",
      message: "نخطط لشهر عسل في فبراير. هل يمكن إضافة ليلتين في سانتوريني في الطريق؟ التواريخ مرنة أسبوعاً كاملاً.",
      travelerCount: 2,
      travelDates: "فبراير ٢٠٢٧ — مرن",
      status: "new",
      createdAt: hoursAgo(2),
    },
  ]);

  console.log("Seeding growth substrate…");
  const { campaigns, contentItems, experiments } = await import("./schema");
  await db.delete(contentItems);
  await db.delete(experiments);
  await db.delete(campaigns);

  const [umrahCampaign, georgiaCampaign] = await db
    .insert(campaigns)
    .values([
      {
        name: "عمرة بلا قلق",
        objective: "رفع طلبات التواصل على عروض العمرة 20% خلال 60 يوماً",
        audience: "أسر خليجية 30–55 تخطط لعمرة شعبان/رمضان",
        channels: ["instagram", "whatsapp", "seo_page"],
        hypothesis: "محتوى طمأنة موثّق (مرافق + فندق قريب مثبت) يتفوق على إعلانات السعر",
        kpi: "طلبات تواصل/أسبوع لعروض العمرة",
        status: "active",
        startsAt: hoursAgo(24 * 10),
        endsAt: daysFromNow2(50),
        createdAt: hoursAgo(24 * 12),
      },
      {
        name: "القوقاز للجميع",
        objective: "بناء طلب مستدام على جورجيا/أذربيجان خارج الموسم",
        audience: "أزواج وشباب 24–40 من السعودية والإمارات",
        channels: ["tiktok", "instagram", "facebook"],
        hypothesis: "فيديوهات قصيرة من الوكيل نفسه تبني ثقة أعلى من الإعلانات الجاهزة",
        kpi: "نسبة مشاهدة→طلب على صفحة جورجيا",
        status: "planned",
        startsAt: daysFromNow2(14),
        endsAt: daysFromNow2(74),
        createdAt: hoursAgo(24 * 3),
      },
    ])
    .returning();

  await db.insert(contentItems).values([
    { campaignId: umrahCampaign.id, title: "دليل: كيف تختار حملة عمرة موثوقة في ٧ نقاط", channel: "blog", contentType: "article", body: "مقال تثقيفي: الفندق المثبت بالمتر من الحرم، المرافق المرخص، السعر الشامل بنداً بنداً، والفرق بين التوثيق والدعاية.", cta: "تصفّح عروض العمرة الموثّقة", risk: "low", status: "published", publishedAt: hoursAgo(24 * 6), createdAt: hoursAgo(24 * 8) },
    { campaignId: umrahCampaign.id, title: "ريلز: جولة فندق الـ ١٥٠ متراً قبل الحجز", channel: "instagram", contentType: "script", body: "سكربت ٤٥ ثانية: لقطة من باب الفندق→ساحات الحرم بعدّ الخطوات بصوت الوكيل، ختاماً بعبارة «اطلب الفيديو الكامل للغرفة قبل الدفع».", cta: "اطلب عرض السعر الكامل", risk: "medium", status: "in_review", createdAt: hoursAgo(24 * 2) },
    { campaignId: georgiaCampaign.id, title: "كاروسيل: ٩ صور من كازبيجي لم تعدّل", channel: "instagram", contentType: "carousel", body: "٩ شرائح بلا فلاتر من رحلة أكتوبر، مع أسعار حقيقية على كل شريحة بدل «اكتب تم».", cta: "صفحة وجهة جورجيا", risk: "low", status: "approved", createdAt: hoursAgo(24 * 5) },
    { campaignId: null, title: "رسالة واتساب: عرضك ينتهي خلال ٧ أيام", channel: "whatsapp", contentType: "post", body: "قالب تنبيه انتهاء صلاحية العروض للوكلاء — يتطلب موافقة بشرية لكل إرسال وفق سياسة المنصة وopt-in.", cta: null, risk: "high", status: "draft", createdAt: hoursAgo(20) },
    { campaignId: umrahCampaign.id, title: "صفحة SEO: السفر إلى السعودية للعمرة", channel: "seo_page", contentType: "article", body: "صفحة وجهة موسعة تربط المحتوى التثقيفي بعروض العمرة المنشورة — تبنى على /destinations/saudi-arabia الحالية.", cta: "عروض العمرة", risk: "low", status: "scheduled", scheduledFor: daysFromNow2(3), createdAt: hoursAgo(24) },
    { campaignId: georgiaCampaign.id, title: "أداء أسبوع ١: ريلز كازبيجي", channel: "tiktok", contentType: "script", body: "قياس: 12k مشاهدة، 310 نقرة ملف، 9 طلبات — تعلّم: اللقطات الشخصية للوكيل تتفوق على لقطات المخزون 3x.", cta: null, risk: "low", status: "measured", publishedAt: hoursAgo(24 * 9), performanceNote: "تفوق نوع «الوكيل يصوّر بنفسه» — يُعمّم على باقي الوكلاء", createdAt: hoursAgo(24 * 11) },
  ]);

  await db.insert(experiments).values([
    { hypothesis: "شريحة «السعر الكامل مكتوب» في أول كاروسيل ترفع النقر→الطلب", metric: "view→contact على صفحة العرض", status: "running", owner: "Growth", startedAt: hoursAgo(24 * 5) },
    { hypothesis: "بريد ترحيبي للوكلاء الجدد مع فيديو دقيقتين يخفض زمن أول عرض", metric: "time-to-first-offer", status: "concluded", result: "انخفض المتوسط من 6.2 إلى 3.1 أيام على 12 وكيلاً (عينة صغيرة)", decision: "scale", owner: "Agent Success", startedAt: hoursAgo(24 * 30), endedAt: hoursAgo(24 * 6) },
    { hypothesis: "إبراز «ينتهي خلال X أيام» الذهبي يرفع الإلحاح", metric: "CTR على البطاقات", status: "concluded", result: "لا فرق ذو دلالة على 2% عينة — يُقتل بدل تركه يزحف", decision: "kill", owner: "Growth", startedAt: hoursAgo(24 * 20), endedAt: hoursAgo(24 * 8) },
  ]);

  console.log("Marketplace seed complete.");
}

seed()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
