/* AUTO-GENERATED by scripts/generate-design-tokens.mjs — do not edit manually. */
export const generatedBrandTokens = {
  "colors": {
    "ink": "#08264A",
    "horizon": "#184F7B",
    "signal": "#2E6FD8",
    "sky": "#7CC8E8",
    "air": "#DFEBF1",
    "paper": "#F5F1E8",
    "cloud": "#FFFFFF",
    "dark": "#071829",
    "text": "#102A43",
    "muted": "#5F6F7E",
    "outline": "#DDE7ED",
    "verified": "#22634A",
    "verifiedBg": "#E6F1EC",
    "warning": "#8A5B00",
    "warningBg": "#FFF3C4",
    "error": "#A42C32",
    "errorBg": "#FBE9E8"
  },
  "spacing": {
    "1": 4,
    "2": 8,
    "3": 12,
    "4": 16,
    "5": 20,
    "6": 24,
    "8": 32,
    "10": 40,
    "12": 48,
    "16": 64,
    "20": 80,
    "24": 96
  },
  "radius": {
    "sm": 8,
    "md": 12,
    "lg": 18,
    "window": 24,
    "hero": 32,
    "pill": 999
  },
  "motion": {
    "fast": 120,
    "base": 200,
    "slow": 320,
    "ease": "cubic-bezier(.2,0,0,1)",
    "focus": 220
  },
  "layout": {
    "max": 1280,
    "reading": 720,
    "touch": 44,
    "gridColumns": 12,
    "gutterMobile": 20,
    "gutterDesktop": 32,
    "decisionMax": 880,
    "copyComfort": 680,
    "touchHighStress": 52
  }
} as const;
