/* AUTO-GENERATED by scripts/generate-design-tokens.mjs — do not edit manually. */
export const generatedBrandTokens = {
  "colors": {
    "ink": "#1A2B6D",
    "horizon": "#2643A8",
    "signal": "#2643A8",
    "sky": "#8EA3E6",
    "air": "#EEF1FB",
    "paper": "#F6F7FA",
    "cloud": "#FFFFFF",
    "dark": "#111B44",
    "text": "#17213B",
    "muted": "#626B7E",
    "outline": "#DDE3EF",
    "verified": "#116B3F",
    "verifiedBg": "#EAF7F0",
    "warning": "#8A5B00",
    "warningBg": "#FFF5E3",
    "error": "#A33A3F",
    "errorBg": "#FCEBEC",
    "earth": "#7A6655"
  },
  "spacing": {
    "1": 4,
    "2": 8,
    "3": 12,
    "4": 16,
    "5": 20,
    "6": 24,
    "8": 32,
    "10": 40,
    "12": 48,
    "16": 64,
    "20": 80,
    "24": 96
  },
  "radius": {
    "sm": 8,
    "md": 12,
    "lg": 18,
    "window": 24,
    "hero": 32,
    "pill": 999
  },
  "motion": {
    "fast": 120,
    "base": 180,
    "slow": 280,
    "ease": "cubic-bezier(.2,0,0,1)"
  },
  "layout": {
    "max": 1320,
    "reading": 680,
    "touch": 52,
    "gridColumns": 12,
    "gutterMobile": 20,
    "gutterDesktop": 32,
    "decision": 880
  }
} as const;
